version: "3.1"

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    restart: "always"
    environment:
      POSTGRES_PASSWORD: "example"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "adswap"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: "adminer"
    ports:
      - "8888:8080"
    restart: "always"

volumes:
  pgdata:
